name: Scrape latest privacy and terms

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest bolt.earth privacy policy
      run: |-
        shot-scraper javascript https://bolt.earth/privacy  "document.querySelector('#content').innerHTML" > bolt-dot-earth-privacy.html
    - name: Fetch latest bolt.earth terms and conditions
      run: |-
        shot-scraper javascript https://bolt.earth/terms  "document.querySelector('#content').innerHTML" > bolt-dot-earth-terms.html
    - name: Fetch latest atherenergy.com App privacy policy
      run: |-
        curl https://www.atherenergy.com/ather-app-privacy-policy > atherenergy-dot-com-privacy.html
    - name: Fetch latest atherenergy.com terms and conditions
      run: |-
        curl https://www.atherenergy.com/terms > atherenergy-dot-com-terms.html
    - name: Fetch latest com.tvsm.iqubeindia android app privacy
      run: |-
        curl https://tvs-evcubemobileapp-prod.azurewebsites.net/Content/AppContent/PrivacyPolicy.html > tvsevcube-app-privacy.html        
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
